Masterminds/semver

constraints.go

Just removes what appears to be an old type, accidentally left over from a previous refactor

Clean up type detritus

---

constraints.go

Totally just a nit, but since it's only matching on the three characters, should be able to get away with this simple switch, no?

Simplify strings.Lower() call

---

version.go

This pulls over a commit from #7 , because strings are not the fastpath. This one change makes a crazy amount of difference:
With absolute numbers, that's:
```
benchmark                                  old ns/op     new ns/op     delta
BenchmarkCheckVersionRange-8               1987          22.1          -98.89%
BenchmarkCheckVersionUnion-8               2047          31.2          -98.48%
BenchmarkValidateVersionRange-8            1998          30.7          -98.46%
BenchmarkCheckVersionCaret-8               1000          17.7          -98.23%
BenchmarkCheckVersionTilde-8               1032          19.1          -98.15%
BenchmarkCheckVersionUnary-8               1012          19.8          -98.04%
BenchmarkValidateVersionCaret-8            1006          25.3          -97.49% …
```

Strings are not the fastpath

---

version.go

Add MustParse() for creating a new Version or panicking on error.
This is useful for parsing statically set build variables

Add MustParse()

---

constraints_test.go
version.go

Per #19, i increasingly think this is a good idea. And, hey, didn't seem that hard to do!

Use uint64 instead of int64 for version components

---

constraints.go
constraints_test.go

A simple range requires a space. For example, 1.2.3-4.5.6 as a
range does not work because the - could signify a pre-release.
Instead this needs to be 1.2.3 - 4.5.6. That was the original
intent.

Fixed #34: Simple range syntax requires a space

---

parse.go

Constraints are logical constructs, not actual versions. As such, keeping around the "original" field data doesn't buy us anything. It does invite issues, though, in the form of simple equality comparisons not working when, say, the constituent versions on a range have slightly different values for "original."
So, this PR strips out "original" from all versions used in constraints.

Strip out original prop on versions in constraints

---

collection.go
collection_test.go
constraints.go
constraints_test.go
error.go
magic.go
parse.go
range.go
set_ops_test.go
union.go
version.go
version_test.go

This PR converts `*Version` to `Version` in all places, and introduces corresponding sentinel values for zero and infinity to act at the lower and upper bound of ranges.
very much WIP, i'm not happy with how the sentinels work (per discussion in #25 )

Depointerize

---

constraints.go
constraints_test.go
error.go
range.go
version.go

Fixes #10.
I ended up not doing the LT/LTE differential at the top of ranges that Dart does (as I described in the issue). This is consistent with npm, and still probably a bit saner.

Add special prerelease handling within ranges

---

constraints_test.go
parse.go

I just noticed that, while #30 defined stringify-time semantics for caret below 1.0.0 to be what we discussed in #21, it did not change the parse-time behavior accordingly. This fixes that - below 1.0.0, a caret behaves like a tilde.

Make caret parsing behave like tilde below 1.0.0

---

constraints.go
constraints_test.go
magic.go
parse.go
range.go
union.go
version.go

I elected to go the route of adding a method to the Constraint interface that allows the caller to decide how the constraint should be converted into a string. A bit of a kluge, but I think really the best of a bad set of options.
Fixes #41.

Basic implementation & tests of implied carets

---

version.go
version_test.go

String comparisons of "99" and "103" see "99" as greater. To handle
cases like this we attempt to turn them into integers and handle
comparisons so 99 is seen as less than 103.

Fixed #57: number comparisons in prerelease

---

version.go
version_test.go

Update NewVersion to parse ints with a 64bit int size.
Version's major, minor and patch fields are all int64 but NewVersion was
parsing them with a 32bit bitsize, update this to 64bits.
This is useful when the patch number is a timestamp in the format:
yyMMddHHmmssSSS which produces numbers like 171003153320169
Add a test cases using 2147483648 (1 more than max 32bit int).

Update major.minor.patch version for 64bit ints

---

constraints.go
constraints_test.go

`2-3` could be interpreted as `2.0.0 - 3.0.0` OR `2.0.0-3` where `3` is the pre-release segment. In order to disambiguate between the two, require that ranges have a space around the range separator. This is the current behavior on v1.
`2-3` is interpreted as `2.0.0-3`
`2 - 3` is interpreted as `2.0.0 - 3.0.0`
I've also added tests to verify that this change resolves #59 as well. After putting this in, no further code changes were necessary. 🎉

Require space in ranges

---

README.md

There has been confusion on the use of pre-releases in comparison
ranges. This attempts to add more detail to help end users
figure them out.

Update the docs on pre-release comparator handling

---

doc.go

The example code for "Checking Version Constraints" failed to re-assign the `err` variable, leading to broken example code.

Fix unchecked error in example code

---

benchmark_test.go
collection.go
collection_test.go
constraints.go
constraints_test.go
version.go
version_test.go

* NewVersion only handles spec compliant SemVer.
* NewVersion has a new method to parse the string that is faster
than regex and uses fewer B/op. For stable versions is uses
fewer allocs and when pre-release or metadata are on the version
it uses 1 more alloc. All around performance is significantly
faster
* CoerceNewVersion handles a semver-ish string. It tries to take
a string that is similar to semver (e.g., 1.2) and turn it into
a valid SemVer instance. This is similar to the previous handling
Closes #75

NewVersion now validates and CoerceNewVersion handles semver-ish

---

benchmark_test.go
collection.go
collection_test.go
constraints.go
constraints_test.go
version.go
version_test.go

There have been issues reported by those installing applications
using go get where semver no longer works because the API changed.
This commit restores the Go API to the old interface.
Note, some of the performance improvement (including allocations
and speed) were lost in this change.
Some functions were renamed including:
* CoerceNewVersion -> NewVersion
* NewVersion -> StrictNewVersion

Restoring v1 Go package API

---

README.md
constraints_test.go

I couldn't find any documentation on the behaviour of the caret operator for pre-1.0.0 dependencies, and it wasn't immediately obvious that it would behave in the same way as for post-1.0.0 dependencies (mainly because in JS it doesn't).
This PR adds a pre-1.0.0 example to the readme and adds a test for the current behaviour.
This may have been discussed elsewhere, but in combination with`dep` using the caret operator by default, the current behaviour here is a little surprising. I can imaging users setting `version = "0.0.1"` in their `Gopkg.toml` and being surprised/unhappy to get `0.0.3`, which might include a host of breaking changes. Maybe that's better fixed in `dep` than here, though.

Clarify caret operator range for pre-1.0.0 dependencies

---

constraints.go
constraints_test.go

Previously the ^ syntax below major version 0 round up to 1. Now
0.x.y and 0.x.z are considered compatible when y >= z. This is how
rust and npm/js operate.
The exception to this is when the minor is below 0. At that point
every release is considered not compatible with anything else.
That means 0.0.x and 0.0.y are not considered compatible even when
x > y.
Previously the PHP/composer pattern had been followed.
In practice some tools, like Helm charts, had followed the
npm/rust method for versioning. This bring the ^ in line with
real world usage desires for this library.

Update range for ^ to follow npm/js and rust

---

.travis.yml
constraints.go
constraints_test.go

^ handling was not dealing with minor and patch versions properly.
Closes #119

Handling ^ correctly with additional tests

---

CHANGELOG.md
benchmark_test.go
go.mod

Fixes issue with module path for v3

---

version.go
version_test.go

This copies the fixed function used on the `release-1` and `mater` branches.

Fixing prerelease comparisons

---

version.go
version_test.go

implement the `driver.Valuer` and `sql.Scanner` interfaces to support using `Version` type as a database field
- `sql.Scanner`: https://golang.org/pkg/database/sql/#Scanner
- `driver.Valuer`: https://golang.org/pkg/database/sql/driver/#Valuer

Add support for SQL

---

constraints.go
constraints_test.go

Previously the validation messages were simply tied to the operator.
There were cases where the message lost its meaning. For example,
a constraing of ^1.12.7 with a version to check of 1.6.6 would have
said the major version did not match. This is not true.
The errors were reworked to be part of the functions performing the
check. This would allow some errors returned to be different from
others. For example, in the case listed here it could not the one
is less than the other. The varying cases is important for ^ as
it has special rules for cases when the major is 0 or the major
and minor are 0. Validation messages appropriate for each of those
cases can be returned.
Note, in v4 of this library there can be one function for checking
and validation as the internals enable that now. The …

More accurate validation messages on constraints

---

.github/workflows/test.yaml
constraints.go

Range was used to iterate over the operations as part of generating
the regex. Range iterations are random. There were cases where the
empty key caused the regex to be generated as invalid.
This change removes the range so that the order is always the same.
Closes #155

Forcing ordered operation when generating regex

---

.golangci.yml
constraints.go
constraints_test.go

This PR aims to fix https://github.com/Masterminds/semver/issues/180
Please take a look when you can 😄

Add minor version check for caret (^) when minor version in constraint is 0(zero)

---

constraints.go
constraints_test.go
version_test.go

Closes #185
Validation of strings was producing false positives when there were too
many sections. A string like 1.2.3.1234 would be found in error but on
like 1.23.3.1234 or 1.2.34.1234 could pass even though it had too many
segments. This is because a string like 1.23.3.1234 would be found as
two different constraints of 1.1 and 3.3.1234.
The fix was to treat validation for the the first and following
constraints separately. For for the following ones a space or command
is now required before it to show it's a second or further one.

Fixing issue where validation of constraint section gave false positives

---

constraints.go
constraints_test.go

This PR adds marshal and unmarshal for constraints (see #130). I tried to built it similar to the already existing implementations for the version type, but there were some challenges
**json.Marshal escapes certain characters**
Unlike version, constraints can also contain '<' and '>' characters. Unfortunately these get escaped when using `json.Marshal` directly (note the `escapeHTML` option in [source](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/encoding/json/encode.go;l=161)). As a result we cannot simply call `json.Marshal` inside our custom MarshalJSON. Therefore I have decided to use a custom encoder that disables HTML escaping.
So far so good. Unfortunately our troubles do not end there. As a matter of fact `encoding.json` calls [additional …

add marshalling for constraints

---

constraints.go
constraints_test.go

Note, this removes the JSON specific handling as the general handling covers the JSON case.
If this is used with JSON and > or < are used than a custom encoder is required. In Go json.Marshal will escape those. For example...
cs, _ := NewConstraint(tc.constraint)
buf := new(bytes.Buffer)
enc := json.NewEncoder(buf)
enc.SetEscapeHTML(false)
err = enc.Encode(cs)
jsonVal = buf.String()

Adding text marshaling and unmarshaling

---

version_test.go

This references #193. semver currently does the proper behavior. This adds tests for the situation to ensure the proper behavior is tested for in the future.

Adding tests for cases around Issue 193

---

Makefile

This is to capture the location in CI in order to cache across fuzz runs

Adding go build cache to fuzz output

---

.github/workflows/fuzz.yaml

This makes fuzz testing additive to previous scans

Add caching to fuzz testing

---

version.go
version_test.go

This changes the Equal method to return true for 2 nil values and false if any one of the values is nil. Previously passing a nil value would have resulted in a panic.

feat: nil version equality

---

README.md

I was a bit surprised that the following doesn't work as expected at first sight:
```go
package main
import (
"github.com/Masterminds/semver/v3"
)
func main() {
c, err := semver.NewConstraint("0.7.2-0.8.0")
if err != nil {
panic(err)
}
v, err := semver.NewVersion("0.7.25")
if err != nil {
panic(err)
}
println(c.Check(v))
}
```
then I realized that we need whitespace between:
```diff
-	c, err := semver.NewConstraint("0.7.2-0.8.0")
+ 	c, err := semver.NewConstraint("0.7.2 - 0.8.0")
```

doc: hyphen range constraint without whitespace

---

README.md

vert is not longer using a supported version of this lib.
Closes #244

Removing reference to vert

---

version.go

less checking things twice
(for example checking +- and then checking again for + and then checking again if pre is set)

simplify StrictNewVersion

---

README.md

PR fixes the CodeQL link in README which currently points to the `Masterminds/semver` repository which can be confusing.

fix the CodeQL link
